### ISSUE TITLE
CI: Go releaser is failing

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/terraform-provider-s3extra#47]
Our latest merges to `main` have been failing like: https://github.com/FormidableLabs/terraform-provider-s3extra/runs/5130349061?check_suite_focus=true

```
Run git tag $(svu next)
  git tag $(svu next)
  git push --tags
  shell: /usr/bin/bash -e {0}
  env:
    GO_VERSION: 1.17
    GOROOT: /opt/hostedtoolcache/go/1.17.6/x64
fatal: tag 'v0.1.2' already exists
Error: Process completed with exit code 128.
```

**Comment by ryan-roemer** [comment]
@seanmcfo Not sure how familiar you are with this go/git release workflow, but maybe take a look tomorrow if you don't have any other OSS to do? Thanks!!!

**Comment by seanmcfo** [comment]
svu require a specific commit message in order to bump the tag:
https://github.com/caarlos0/svu
#### commit messages vs what they do

| Commit message                                                                         | Tag increase |
| -------------------------------------------------------------------------------------- | ------------ |
| `fix: fixed something`                                                                 | Patch        |
| `feat: added new button to do X`                                                       | Minor        |
| `fix: fixed thing xyz`<br><br>`BREAKING CHANGE: this will break users because of blah` | Major        |
| `fix!: fixed something`                                                                | Major        |
| `feat!: added blah`                                                                    | Major        |
| `chore: foo`                                                                           | Nothing      |

**Comment by ryan-roemer** [comment]
@seanmcfo Thanks. Yeah, that commit did cause us to do a `1.3.0` new release to the terraform registry.

What I'm thinking is that we just have the release script _not fail_ if there's no version bump (like for `chore:` or non-prefixed). There's probably some shell conditional we can do early on and maybe end the job with a success? Or, maybe capture a "no change" (like bash `svu current` is equal to `svu next`) in an env var and then do GH action condtionals on the last two run commands (that do the git tag and release) so they just don't run. Or, something analogous :)

**Comment by seanmcfo** [comment]
How about `git tag $(svu next) || :`?

**Comment by seanmcfo** [comment]
Actually scrub the above I was missing 
```          # Allow goreleaser to access older tag information.
          fetch-depth: 0```

**Comment by ryan-roemer** [comment]
We _could_ do the `git tag ... || something` but ideally, we would want like an `svu` error to actually blow up, not be interpreted as "same version".

Maybe as step 1 we just capture `svu next` and `svu current` in environmental variables, and echo them out in a subsequent `run`, before `git tag` in a test PR and merge that just to check we have the right values?
